// وحدات جدارات تخصص الكهرباء - بيانات كاملة
const FILES = [
  // ========== الصف الأول - فني آلات كهربية ==========
  {id:"1Wqwx_08CdPuFd47Zg1s4Avo_nAYgeN9I",name:"دليل الطالب - أساسيات الورشة الكهربية",grade:1,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1Wqwx_08CdPuFd47Zg1s4Avo_nAYgeN9I/view",downloadLink:"https://drive.google.com/uc?export=download&id=1Wqwx_08CdPuFd47Zg1s4Avo_nAYgeN9I"},
  {id:"1d1QgeR8L1DA2IOGrzgqZv-n-2LaX_08w",name:"دليل الطالب - أجهزة القياس",grade:1,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1d1QgeR8L1DA2IOGrzgqZv-n-2LaX_08w/view",downloadLink:"https://drive.google.com/uc?export=download&id=1d1QgeR8L1DA2IOGrzgqZv-n-2LaX_08w"},
  {id:"1SubVjaOrd73QJdWFDpupg-1FVQejyVoF",name:"دليل الطالب - مكونات الدوائر الكهربية",grade:1,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1SubVjaOrd73QJdWFDpupg-1FVQejyVoF/view",downloadLink:"https://drive.google.com/uc?export=download&id=1SubVjaOrd73QJdWFDpupg-1FVQejyVoF"},
  {id:"1PfuoDqZFEQPcaRM86XLuVT0GIsXkKQsT",name:"دليل الطالب - بناء وحدة كهربية بسيطة (الوحدة السادسة)",grade:1,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1PfuoDqZFEQPcaRM86XLuVT0GIsXkKQsT/view",downloadLink:"https://drive.google.com/uc?export=download&id=1PfuoDqZFEQPcaRM86XLuVT0GIsXkKQsT"},
  {id:"1284iGEkesFLpR_gZhGWRm7SWUjmwohfE",name:"دليل الطالب - المغناطيسية الكهربية",grade:1,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1284iGEkesFLpR_gZhGWRm7SWUjmwohfE/view",downloadLink:"https://drive.google.com/uc?export=download&id=1284iGEkesFLpR_gZhGWRm7SWUjmwohfE"},
  {id:"1oBiHZLrdVKuVDtovoecjmXsh_e6C4sCZ",name:"دليل الطالب - الرسم الفني الكهربي (الوحدة الرابعة)",grade:1,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1oBiHZLrdVKuVDtovoecjmXsh_e6C4sCZ/view",downloadLink:"https://drive.google.com/uc?export=download&id=1oBiHZLrdVKuVDtovoecjmXsh_e6C4sCZ"},
  {id:"1uZPkilxWySQ5QaO1_nJ5F4sMkGNNumUK",name:"دليل المعلم - أساسيات الورشة الكهربية",grade:1,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1uZPkilxWySQ5QaO1_nJ5F4sMkGNNumUK/view",downloadLink:"https://drive.google.com/uc?export=download&id=1uZPkilxWySQ5QaO1_nJ5F4sMkGNNumUK"},
  {id:"1T3l6BOlMIr2giwrn_yBLimYApnLYmcmg",name:"دليل المعلم - أجهزة القياس الكهربية",grade:1,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1T3l6BOlMIr2giwrn_yBLimYApnLYmcmg/view",downloadLink:"https://drive.google.com/uc?export=download&id=1T3l6BOlMIr2giwrn_yBLimYApnLYmcmg"},
  {id:"1G8aEByosBHPGOjQZ9JAGNsL3oePvanyM",name:"دليل المعلم - المكونات والدوائر الكهربية",grade:1,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1G8aEByosBHPGOjQZ9JAGNsL3oePvanyM/view",downloadLink:"https://drive.google.com/uc?export=download&id=1G8aEByosBHPGOjQZ9JAGNsL3oePvanyM"},
  {id:"1f75w05K1lRamIBRCASbsXNJ-ZMiyVoKb",name:"دليل المعلم - بناء وحدة كهربية بسيطة",grade:1,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1f75w05K1lRamIBRCASbsXNJ-ZMiyVoKb/view",downloadLink:"https://drive.google.com/uc?export=download&id=1f75w05K1lRamIBRCASbsXNJ-ZMiyVoKb"},
  {id:"1nBeMlyBMUEhJdwvNDlZQpEuhVHn-H97q",name:"دليل المعلم - المغناطيسية الكهربية",grade:1,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1nBeMlyBMUEhJdwvNDlZQpEuhVHn-H97q/view",downloadLink:"https://drive.google.com/uc?export=download&id=1nBeMlyBMUEhJdwvNDlZQpEuhVHn-H97q"},
  {id:"1ZcLEo_kPiqcoivPTqFsu6VqbC0fxHhiw",name:"دليل المعلم - الرسومات الفنية الكهربية يدوياً وبالكمبيوتر",grade:1,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1ZcLEo_kPiqcoivPTqFsu6VqbC0fxHhiw/view",downloadLink:"https://drive.google.com/uc?export=download&id=1ZcLEo_kPiqcoivPTqFsu6VqbC0fxHhiw"},

  // ========== الصف الأول - فني تركيبات كهربية ==========
  {id:"1lgPI8VbjN5N4x27ou-xI16h1c992wyZe",name:"دليل الطالب - أساسيات الورشة الكهربية",grade:1,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1lgPI8VbjN5N4x27ou-xI16h1c992wyZe/view",downloadLink:"https://drive.google.com/uc?export=download&id=1lgPI8VbjN5N4x27ou-xI16h1c992wyZe"},
  {id:"1aZeGLhvdMYFa_tU7BK0qDcHTZrYvaF3e",name:"دليل الطالب - أجهزة القياس",grade:1,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1aZeGLhvdMYFa_tU7BK0qDcHTZrYvaF3e/view",downloadLink:"https://drive.google.com/uc?export=download&id=1aZeGLhvdMYFa_tU7BK0qDcHTZrYvaF3e"},
  {id:"13lD0j_ywEwM_ACQtdws6lCjpYTO6wTfQ",name:"دليل الطالب - مكونات الدوائر الكهربية",grade:1,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/13lD0j_ywEwM_ACQtdws6lCjpYTO6wTfQ/view",downloadLink:"https://drive.google.com/uc?export=download&id=13lD0j_ywEwM_ACQtdws6lCjpYTO6wTfQ"},
  {id:"1S7JgZYpZgLhGWcJwgZ40jghQWToK-Afv",name:"دليل الطالب - بناء وحدة كهربية بسيطة",grade:1,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1S7JgZYpZgLhGWcJwgZ40jghQWToK-Afv/view",downloadLink:"https://drive.google.com/uc?export=download&id=1S7JgZYpZgLhGWcJwgZ40jghQWToK-Afv"},
  {id:"1epGxIWhqvuhEIvGbLHycQHvp9mQgtzY2",name:"دليل الطالب - الرسم الفني الكهربي (الوحدة الرابعة)",grade:1,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1epGxIWhqvuhEIvGbLHycQHvp9mQgtzY2/view",downloadLink:"https://drive.google.com/uc?export=download&id=1epGxIWhqvuhEIvGbLHycQHvp9mQgtzY2"},
  {id:"1cJXHe7dD2BFNnTMvVsFicz74H2VClTAY",name:"دليل الطالب - الدوائر الإلكترونية (الوحدة الخامسة)",grade:1,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1cJXHe7dD2BFNnTMvVsFicz74H2VClTAY/view",downloadLink:"https://drive.google.com/uc?export=download&id=1cJXHe7dD2BFNnTMvVsFicz74H2VClTAY"},
  {id:"1uZRB_ItWetR_Hy3P0fp3tySDptmOdwiO",name:"دليل المعلم - أساسيات الورشة الكهربية",grade:1,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1uZRB_ItWetR_Hy3P0fp3tySDptmOdwiO/view",downloadLink:"https://drive.google.com/uc?export=download&id=1uZRB_ItWetR_Hy3P0fp3tySDptmOdwiO"},
  {id:"1nAmneEgnh4uebhbzQar-BVcFoNp74Ui5",name:"دليل المعلم - أجهزة القياس الكهربية",grade:1,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1nAmneEgnh4uebhbzQar-BVcFoNp74Ui5/view",downloadLink:"https://drive.google.com/uc?export=download&id=1nAmneEgnh4uebhbzQar-BVcFoNp74Ui5"},
  {id:"1C-UrO1j2IZbChDDL6ccJUb-6rsXVyjov",name:"دليل المعلم - المكونات والدوائر الكهربية",grade:1,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1C-UrO1j2IZbChDDL6ccJUb-6rsXVyjov/view",downloadLink:"https://drive.google.com/uc?export=download&id=1C-UrO1j2IZbChDDL6ccJUb-6rsXVyjov"},
  {id:"1-_jqV4puQcgHmfCYYfv30ZEeC8MaNLQK",name:"دليل المعلم - بناء وحدة كهربية بسيطة",grade:1,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1-_jqV4puQcgHmfCYYfv30ZEeC8MaNLQK/view",downloadLink:"https://drive.google.com/uc?export=download&id=1-_jqV4puQcgHmfCYYfv30ZEeC8MaNLQK"},
  {id:"1Jp9dAukSdR4e3P6-gGjjm2DKkTbFezK7",name:"دليل المعلم - الرسومات الفنية الكهربية يدوياً وبالكمبيوتر",grade:1,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1Jp9dAukSdR4e3P6-gGjjm2DKkTbFezK7/view",downloadLink:"https://drive.google.com/uc?export=download&id=1Jp9dAukSdR4e3P6-gGjjm2DKkTbFezK7"},
  {id:"150_dm0HbAQiC6V61GSl5gjcxk0DIRIG4",name:"دليل المعلم - بناء واختبار الدوائر الإلكترونية الأساسية",grade:1,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/150_dm0HbAQiC6V61GSl5gjcxk0DIRIG4/view",downloadLink:"https://drive.google.com/uc?export=download&id=150_dm0HbAQiC6V61GSl5gjcxk0DIRIG4"},

  // ========== الصف الأول - فني صيانة ==========
  {id:"1jzcSHf3Uuv6pCkCA7Yhtwh95QeZjaBED",name:"دليل الطالب - برنامج فني صيانة وإصلاح الأجهزة المنزلية",grade:1,specialty:"صيانة",type:"طالب",term:null,folderLink:"https://drive.google.com/file/d/1jzcSHf3Uuv6pCkCA7Yhtwh95QeZjaBED/view",downloadLink:"https://drive.google.com/uc?export=download&id=1jzcSHf3Uuv6pCkCA7Yhtwh95QeZjaBED"},
  {id:"1an1l2vQzsbIS0EoYNM8p6uP88vpauiW3",name:"دليل المعلم - برنامج فني صيانة وإصلاح الأجهزة المنزلية",grade:1,specialty:"صيانة",type:"معلم",term:null,folderLink:"https://drive.google.com/file/d/1an1l2vQzsbIS0EoYNM8p6uP88vpauiW3/view",downloadLink:"https://drive.google.com/uc?export=download&id=1an1l2vQzsbIS0EoYNM8p6uP88vpauiW3"},
  {id:"176ON64GxE_0eCzAJ4l5tJI7BXRdCXNgw",name:"كتيب أدلة التقييم (2025-2026) - فني صيانة وإصلاح الأجهزة المنزلية",grade:1,specialty:"صيانة",type:"تقييم",term:null,folderLink:"https://drive.google.com/file/d/176ON64GxE_0eCzAJ4l5tJI7BXRdCXNgw/view",downloadLink:"https://drive.google.com/uc?export=download&id=176ON64GxE_0eCzAJ4l5tJI7BXRdCXNgw"},

  // ========== الصف الثاني - آلات ==========
  {id:"1leAgVwALGBETWMCW8bQobFYe9EX60Qmd",name:"دليل الطالب - آلات التيار المستمر",grade:2,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1leAgVwALGBETWMCW8bQobFYe9EX60Qmd/view",downloadLink:"https://drive.google.com/uc?export=download&id=1leAgVwALGBETWMCW8bQobFYe9EX60Qmd"},
  {id:"1Q-Rp0MGmP5PF2v2NkiIN3dYyO23ZpIQt",name:"دليل الطالب - الصيانة الوقائية",grade:2,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1Q-Rp0MGmP5PF2v2NkiIN3dYyO23ZpIQt/view",downloadLink:"https://drive.google.com/uc?export=download&id=1Q-Rp0MGmP5PF2v2NkiIN3dYyO23ZpIQt"},
  {id:"1zFqKwQFXkRVrZrBrihXHsWSodsPWzwdB",name:"دليل الطالب - المحولات الكهربية",grade:2,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1zFqKwQFXkRVrZrBrihXHsWSodsPWzwdB/view",downloadLink:"https://drive.google.com/uc?export=download&id=1zFqKwQFXkRVrZrBrihXHsWSodsPWzwdB"},
  {id:"1QZAKqFF1tSHHMK9_XzH7HASVS7Me8cOR",name:"دليل الطالب - قياس القدرة الكهربية والسرعة",grade:2,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1QZAKqFF1tSHHMK9_XzH7HASVS7Me8cOR/view",downloadLink:"https://drive.google.com/uc?export=download&id=1QZAKqFF1tSHHMK9_XzH7HASVS7Me8cOR"},
  {id:"1QIgy-Gbwot8j54YnNtZ8FUAZurqdudh3",name:"دليل الطالب - مخططات آلات التيار المستمر",grade:2,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1QIgy-Gbwot8j54YnNtZ8FUAZurqdudh3/view",downloadLink:"https://drive.google.com/uc?export=download&id=1QIgy-Gbwot8j54YnNtZ8FUAZurqdudh3"},
  {id:"1V4R9fseXctvYScuQwgMT79bvCPEb848e",name:"دليل الطالب - وقاية وحماية الآلات الكهربية",grade:2,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1V4R9fseXctvYScuQwgMT79bvCPEb848e/view",downloadLink:"https://drive.google.com/uc?export=download&id=1V4R9fseXctvYScuQwgMT79bvCPEb848e"},
  {id:"1gGkl8Jvq8Wo4T6d6VBMUiaIP_7kJLceO",name:"دليل المعلم - آلات التيار المستمر",grade:2,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1gGkl8Jvq8Wo4T6d6VBMUiaIP_7kJLceO/view",downloadLink:"https://drive.google.com/uc?export=download&id=1gGkl8Jvq8Wo4T6d6VBMUiaIP_7kJLceO"},
  {id:"1q-TXiiJJUHUEE0Ax6rGD5v1Yu9PtKqEq",name:"دليل المعلم - الصيانة الوقائية",grade:2,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1q-TXiiJJUHUEE0Ax6rGD5v1Yu9PtKqEq/view",downloadLink:"https://drive.google.com/uc?export=download&id=1q-TXiiJJUHUEE0Ax6rGD5v1Yu9PtKqEq"},
  {id:"1_Y7o0e8wJaHBzOQ4QJGPMfs8YowIEdZv",name:"دليل المعلم - المحولات الكهربية",grade:2,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1_Y7o0e8wJaHBzOQ4QJGPMfs8YowIEdZv/view",downloadLink:"https://drive.google.com/uc?export=download&id=1_Y7o0e8wJaHBzOQ4QJGPMfs8YowIEdZv"},
  {id:"1kS6kM-A5bS2GQhArKcUz92uugqC8NbI2",name:"دليل المعلم - قياس القدرة الكهربية والسرعة",grade:2,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1kS6kM-A5bS2GQhArKcUz92uugqC8NbI2/view",downloadLink:"https://drive.google.com/uc?export=download&id=1kS6kM-A5bS2GQhArKcUz92uugqC8NbI2"},
  {id:"12iQ-RGfX0w_jB5JBZAFzplMkZ5PTsqgU",name:"دليل المعلم - مخططات آلات التيار المستمر",grade:2,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/12iQ-RGfX0w_jB5JBZAFzplMkZ5PTsqgU/view",downloadLink:"https://drive.google.com/uc?export=download&id=12iQ-RGfX0w_jB5JBZAFzplMkZ5PTsqgU"},
  {id:"1iJ0_Evtr_IKqDGEolR1CCOCMkmpEKNgB",name:"دليل المعلم - وقاية وحماية الآلات الكهربية",grade:2,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1iJ0_Evtr_IKqDGEolR1CCOCMkmpEKNgB/view",downloadLink:"https://drive.google.com/uc?export=download&id=1iJ0_Evtr_IKqDGEolR1CCOCMkmpEKNgB"},

  // ========== الصف الثاني - تركيبات ==========
  {id:"1ctCbM0j1zbKXLZFmm8p2kOV4ZQhqBoze",name:"دليل الطالب - إعداد المواد والأدوات",grade:2,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1ctCbM0j1zbKXLZFmm8p2kOV4ZQhqBoze/view",downloadLink:"https://drive.google.com/uc?export=download&id=1ctCbM0j1zbKXLZFmm8p2kOV4ZQhqBoze"},
  {id:"1QPl2GOt4eCzANqfGZqJ9YW-7N-7DT192",name:"دليل الطالب - المفاتيح والمآخذ وقواطع التسرب الأرضي",grade:2,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1QPl2GOt4eCzANqfGZqJ9YW-7N-7DT192/view",downloadLink:"https://drive.google.com/uc?export=download&id=1QPl2GOt4eCzANqfGZqJ9YW-7N-7DT192"},
  {id:"1jlDxkII4IBaov9-CbtuWch_Bbq_Une8w",name:"دليل الطالب - تركيب المواسير والقنوات",grade:2,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1jlDxkII4IBaov9-CbtuWch_Bbq_Une8w/view",downloadLink:"https://drive.google.com/uc?export=download&id=1jlDxkII4IBaov9-CbtuWch_Bbq_Une8w"},
  {id:"1vCABIpOgLEL_xotJFgRQP7Yu0RJptNUo",name:"دليل الطالب - تركيب أنظمة الإضاءة",grade:2,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1vCABIpOgLEL_xotJFgRQP7Yu0RJptNUo/view",downloadLink:"https://drive.google.com/uc?export=download&id=1vCABIpOgLEL_xotJFgRQP7Yu0RJptNUo"},
  {id:"17QvAgIpk6II7ZIIyvcLL8n5uKnBJJapI",name:"دليل الطالب - تركيب مصادر الطاقة الاحتياطية",grade:2,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/17QvAgIpk6II7ZIIyvcLL8n5uKnBJJapI/view",downloadLink:"https://drive.google.com/uc?export=download&id=17QvAgIpk6II7ZIIyvcLL8n5uKnBJJapI"},
  {id:"1X73vhI4smrvtXog0Am36e41HSxitn1NW",name:"دليل الطالب - تطبيق المحولات في الأنظمة الكهربية",grade:2,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1X73vhI4smrvtXog0Am36e41HSxitn1NW/view",downloadLink:"https://drive.google.com/uc?export=download&id=1X73vhI4smrvtXog0Am36e41HSxitn1NW"},
  {id:"1NDIaYG5UuW-oWn3oeclIOr69n_r9FmCX",name:"دليل الطالب - تركيب نظم الحماية الكهربائية والتأريض",grade:2,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1NDIaYG5UuW-oWn3oeclIOr69n_r9FmCX/view",downloadLink:"https://drive.google.com/uc?export=download&id=1NDIaYG5UuW-oWn3oeclIOr69n_r9FmCX"},
  {id:"1x9HKzqgn0rdyiEJMMLMMT_k5GhtvBHiX",name:"دليل المعلم - إعداد المواد والأدوات المطلوبة",grade:2,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1x9HKzqgn0rdyiEJMMLMMT_k5GhtvBHiX/view",downloadLink:"https://drive.google.com/uc?export=download&id=1x9HKzqgn0rdyiEJMMLMMT_k5GhtvBHiX"},
  {id:"1I968GHcmgLdazPUivYGRBRrCHBLSKnDp",name:"دليل المعلم - المفاتيح والمآخذ وقواطع التسرب",grade:2,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1I968GHcmgLdazPUivYGRBRrCHBLSKnDp/view",downloadLink:"https://drive.google.com/uc?export=download&id=1I968GHcmgLdazPUivYGRBRrCHBLSKnDp"},
  {id:"1Hcc7dxuiZdZOf0q3bPs9VO0U59Q1ghGE",name:"دليل المعلم - تركيب المواسير والقنوات والكابلات",grade:2,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1Hcc7dxuiZdZOf0q3bPs9VO0U59Q1ghGE/view",downloadLink:"https://drive.google.com/uc?export=download&id=1Hcc7dxuiZdZOf0q3bPs9VO0U59Q1ghGE"},
  {id:"19vksTtN74EziC0NvYVrUyo6K3N4MDReU",name:"دليل المعلم - تركيب أنظمة الإضاءة",grade:2,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/19vksTtN74EziC0NvYVrUyo6K3N4MDReU/view",downloadLink:"https://drive.google.com/uc?export=download&id=19vksTtN74EziC0NvYVrUyo6K3N4MDReU"},
  {id:"1vARtY3-Kn9a0EYVORiufJH2Qy1u5CJ8J",name:"دليل المعلم - تركيب مصادر الطاقة الاحتياطية وأجهزة التحكم",grade:2,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1vARtY3-Kn9a0EYVORiufJH2Qy1u5CJ8J/view",downloadLink:"https://drive.google.com/uc?export=download&id=1vARtY3-Kn9a0EYVORiufJH2Qy1u5CJ8J"},
  {id:"1dFo3EJ-kBllT4PCZGmoVT7KHx6g9B_kg",name:"دليل المعلم - تركيب نظم الحماية الكهربائية والتأريض",grade:2,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1dFo3EJ-kBllT4PCZGmoVT7KHx6g9B_kg/view",downloadLink:"https://drive.google.com/uc?export=download&id=1dFo3EJ-kBllT4PCZGmoVT7KHx6g9B_kg"},
  {id:"1fOKg6Tfgzd79D185d_7CAcCCd5_bNbCH",name:"دليل المعلم - تطبيق المحولات في الأنظمة الكهربية",grade:2,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1fOKg6Tfgzd79D185d_7CAcCCd5_bNbCH/view",downloadLink:"https://drive.google.com/uc?export=download&id=1fOKg6Tfgzd79D185d_7CAcCCd5_bNbCH"},

  // ========== الصف الثالث - آلات ==========
  {id:"1K265GSBfrLPf93UgtadTd5f1jDBj4_Ar",name:"دليل الطالب - نظام بناء التكاليف",grade:3,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1K265GSBfrLPf93UgtadTd5f1jDBj4_Ar/view",downloadLink:"https://drive.google.com/uc?export=download&id=1K265GSBfrLPf93UgtadTd5f1jDBj4_Ar"},
  {id:"1INwuxdi4j4xeF7P4dVdWMXDID37dVuIY",name:"دليل الطالب - تشخيص أعطال وصيانة الآلات التزامنية",grade:3,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1INwuxdi4j4xeF7P4dVdWMXDID37dVuIY/view",downloadLink:"https://drive.google.com/uc?export=download&id=1INwuxdi4j4xeF7P4dVdWMXDID37dVuIY"},
  {id:"1Vk6pRbfW1hixtRXvQNZwDfySWIY7B48Y",name:"دليل الطالب - تشخيص أعطال وصيانة آلات التيار المتردد (ثلاث أوجه)",grade:3,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1Vk6pRbfW1hixtRXvQNZwDfySWIY7B48Y/view",downloadLink:"https://drive.google.com/uc?export=download&id=1Vk6pRbfW1hixtRXvQNZwDfySWIY7B48Y"},
  {id:"1OlSMZJmBQ8tiCPK7C8PlRMcngHO_gnnx",name:"دليل الطالب - تشخيص أعطال وصيانة آلات التيار المتردد (وجه واحد)",grade:3,specialty:"آلات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1OlSMZJmBQ8tiCPK7C8PlRMcngHO_gnnx/view",downloadLink:"https://drive.google.com/uc?export=download&id=1OlSMZJmBQ8tiCPK7C8PlRMcngHO_gnnx"},
  {id:"12LFTgyjcVnX_gD27Ir-3kpuPDVtZmLRw",name:"دليل الطالب - لف آلات التيار المتردد الحثية والمتزامنة",grade:3,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/12LFTgyjcVnX_gD27Ir-3kpuPDVtZmLRw/view",downloadLink:"https://drive.google.com/uc?export=download&id=12LFTgyjcVnX_gD27Ir-3kpuPDVtZmLRw"},
  {id:"1nYYE9KvYBlOp74TPi0PtNqk8pjrMatlK",name:"دليل الطالب - مخططات آلات التيار المتردد الحثية والمتزامنة",grade:3,specialty:"آلات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1nYYE9KvYBlOp74TPi0PtNqk8pjrMatlK/view",downloadLink:"https://drive.google.com/uc?export=download&id=1nYYE9KvYBlOp74TPi0PtNqk8pjrMatlK"},
  {id:"1YEhx4jGQQdashc0Pd2SfMbcTYmPEuYXf",name:"دليل المعلم - نظام بناء التكاليف",grade:3,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1YEhx4jGQQdashc0Pd2SfMbcTYmPEuYXf/view",downloadLink:"https://drive.google.com/uc?export=download&id=1YEhx4jGQQdashc0Pd2SfMbcTYmPEuYXf"},
  {id:"1qrhLuZ4yEOkDP3BmrV0VrHfowlREC8yZ",name:"دليل المعلم - تشخيص أعطال وصيانة الآلات التزامنية",grade:3,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1qrhLuZ4yEOkDP3BmrV0VrHfowlREC8yZ/view",downloadLink:"https://drive.google.com/uc?export=download&id=1qrhLuZ4yEOkDP3BmrV0VrHfowlREC8yZ"},
  {id:"1bs9VbPNgwHvR7QsQ6XLWmO7Wxw3ZI9_t",name:"دليل المعلم - تشخيص أعطال وصيانة آلات التيار المتردد (ثلاث أوجه)",grade:3,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1bs9VbPNgwHvR7QsQ6XLWmO7Wxw3ZI9_t/view",downloadLink:"https://drive.google.com/uc?export=download&id=1bs9VbPNgwHvR7QsQ6XLWmO7Wxw3ZI9_t"},
  {id:"1gScjRjIR7Kkj7sQj0c7BHDzEL2g1mOly",name:"دليل المعلم - تشخيص أعطال وصيانة آلات التيار المتردد (وجه واحد)",grade:3,specialty:"آلات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1gScjRjIR7Kkj7sQj0c7BHDzEL2g1mOly/view",downloadLink:"https://drive.google.com/uc?export=download&id=1gScjRjIR7Kkj7sQj0c7BHDzEL2g1mOly"},
  {id:"1_HjAZZgQeImR4fg-mxIvLX1Ggeu4a-vM",name:"دليل المعلم - لف آلات التيار المتردد الحثية والمتزامنة",grade:3,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1_HjAZZgQeImR4fg-mxIvLX1Ggeu4a-vM/view",downloadLink:"https://drive.google.com/uc?export=download&id=1_HjAZZgQeImR4fg-mxIvLX1Ggeu4a-vM"},
  {id:"17J5YJQVA3htLHJPjdVFZVnVnDI-zdKry",name:"دليل المعلم - مخططات آلات التيار المتردد الحثية والمتزامنة",grade:3,specialty:"آلات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/17J5YJQVA3htLHJPjdVFZVnVnDI-zdKry/view",downloadLink:"https://drive.google.com/uc?export=download&id=17J5YJQVA3htLHJPjdVFZVnVnDI-zdKry"},

  // ========== الصف الثالث - تركيبات ==========
  {id:"1mfai4V9y2DndFPfrR1Dy23HSiGZnJnVi",name:"دليل الطالب - تركيب واختبار دوائر كاميرات المراقبة",grade:3,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1mfai4V9y2DndFPfrR1Dy23HSiGZnJnVi/view",downloadLink:"https://drive.google.com/uc?export=download&id=1mfai4V9y2DndFPfrR1Dy23HSiGZnJnVi"},
  {id:"1F_1W-6p2w9wLuX_B4An0hOqmNrTkO49U",name:"دليل الطالب - تركيب الاتصالات الداخلية والدش",grade:3,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1F_1W-6p2w9wLuX_B4An0hOqmNrTkO49U/view",downloadLink:"https://drive.google.com/uc?export=download&id=1F_1W-6p2w9wLuX_B4An0hOqmNrTkO49U"},
  {id:"1R7nWFg7o0YKsyQMGO24drWi4XlR8eLym",name:"دليل الطالب - تطبيق معايير التركيبات الكهربائية وفحصها",grade:3,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1R7nWFg7o0YKsyQMGO24drWi4XlR8eLym/view",downloadLink:"https://drive.google.com/uc?export=download&id=1R7nWFg7o0YKsyQMGO24drWi4XlR8eLym"},
  {id:"1cZ1EZ1u31AGkjwftkFK8L7J0nBXrWAoa",name:"دليل الطالب - تركيب وصيانة دوائر الإنذار ضد الحريق والسرقة",grade:3,specialty:"تركيبات",type:"طالب",term:1,folderLink:"https://drive.google.com/file/d/1cZ1EZ1u31AGkjwftkFK8L7J0nBXrWAoa/view",downloadLink:"https://drive.google.com/uc?export=download&id=1cZ1EZ1u31AGkjwftkFK8L7J0nBXrWAoa"},
  {id:"1dFaH164ejjp6jVcRJnJbiDUg5pL9DU3F",name:"دليل الطالب - تأدية الفحص العام وصيانة التركيبات",grade:3,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/1dFaH164ejjp6jVcRJnJbiDUg5pL9DU3F/view",downloadLink:"https://drive.google.com/uc?export=download&id=1dFaH164ejjp6jVcRJnJbiDUg5pL9DU3F"},
  {id:"15CmCy7Gu4KatBavScAcBP8YEQm773oTJ",name:"دليل الطالب - تنفيذ الاختبارات للتركيبات الكهربية",grade:3,specialty:"تركيبات",type:"طالب",term:2,folderLink:"https://drive.google.com/file/d/15CmCy7Gu4KatBavScAcBP8YEQm773oTJ/view",downloadLink:"https://drive.google.com/uc?export=download&id=15CmCy7Gu4KatBavScAcBP8YEQm773oTJ"},
  {id:"1WPK0tfdcvT002XGZ2yHOaPg2oixUBltj",name:"دليل المعلم - تركيب وصيانة دوائر الاتصالات الداخلية",grade:3,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1WPK0tfdcvT002XGZ2yHOaPg2oixUBltj/view",downloadLink:"https://drive.google.com/uc?export=download&id=1WPK0tfdcvT002XGZ2yHOaPg2oixUBltj"},
  {id:"18H-axtkGbY8T7VbOlJnj3Bo2YnFDTABo",name:"دليل المعلم - تركيب واختبار دوائر كاميرات المراقبة",grade:3,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/18H-axtkGbY8T7VbOlJnj3Bo2YnFDTABo/view",downloadLink:"https://drive.google.com/uc?export=download&id=18H-axtkGbY8T7VbOlJnj3Bo2YnFDTABo"},
  {id:"1sboEZ_dhmvLpkRa4HYpviPj3KOQtW-Ck",name:"دليل المعلم - تركيب وصيانة دوائر الإنذار ضد الحريق والسرقة",grade:3,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1sboEZ_dhmvLpkRa4HYpviPj3KOQtW-Ck/view",downloadLink:"https://drive.google.com/uc?export=download&id=1sboEZ_dhmvLpkRa4HYpviPj3KOQtW-Ck"},
  {id:"1pzTOvMpdQf6jvWhM-I-Pd3dSFoqsps4I",name:"دليل المعلم - تطبيق معايير التركيبات الكهربائية وفحصها",grade:3,specialty:"تركيبات",type:"معلم",term:1,folderLink:"https://drive.google.com/file/d/1pzTOvMpdQf6jvWhM-I-Pd3dSFoqsps4I/view",downloadLink:"https://drive.google.com/uc?export=download&id=1pzTOvMpdQf6jvWhM-I-Pd3dSFoqsps4I"},
  {id:"1uqBi-oMyKOXenZACzbNHO8vuUJmwR6MU",name:"دليل المعلم - تنفيذ الاختبارات للتركيبات الكهربية",grade:3,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1uqBi-oMyKOXenZACzbNHO8vuUJmwR6MU/view",downloadLink:"https://drive.google.com/uc?export=download&id=1uqBi-oMyKOXenZACzbNHO8vuUJmwR6MU"},
  {id:"1X9IPM6LJjWx6n564KequJEWct26z8Jmf",name:"دليل المعلم - تأدية الفحص العام وصيانة التركيبات الكهربية",grade:3,specialty:"تركيبات",type:"معلم",term:2,folderLink:"https://drive.google.com/file/d/1X9IPM6LJjWx6n564KequJEWct26z8Jmf/view",downloadLink:"https://drive.google.com/uc?export=download&id=1X9IPM6LJjWx6n564KequJEWct26z8Jmf"},

  // مجلدات رئيسية
  {id:"folder-g1",name:"📁 المجلد الكامل - الصف الأول (كل التخصصات)",grade:1,specialty:"",type:"",term:null,isFolder:true,folderLink:"https://drive.google.com/drive/folders/1aM-kb5hoM5BLWlPUSgHTRgxUWKYA7Nme?usp=sharing",downloadLink:"https://drive.google.com/drive/folders/1aM-kb5hoM5BLWlPUSgHTRgxUWKYA7Nme?usp=sharing"},
  {id:"folder-g2",name:"📁 المجلد الكامل - الصف الثاني (كل التخصصات)",grade:2,specialty:"",type:"",term:null,isFolder:true,folderLink:"https://drive.google.com/drive/folders/1XY2hYfvHLRREpHenDz1NS7wPboQ2s7Vs?usp=sharing",downloadLink:"https://drive.google.com/drive/folders/1XY2hYfvHLRREpHenDz1NS7wPboQ2s7Vs?usp=sharing"},
  {id:"folder-g3",name:"📁 المجلد الكامل - الصف الثالث (كل التخصصات)",grade:3,specialty:"",type:"",term:null,isFolder:true,folderLink:"https://drive.google.com/drive/folders/1qKuu7LWDVhAtsQHKAcDoWmSyTCpWXHvo?usp=sharing",downloadLink:"https://drive.google.com/drive/folders/1qKuu7LWDVhAtsQHKAcDoWmSyTCpWXHvo?usp=sharing"}
];